# Generated by Django 4.2.2 on 2023-06-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_line', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdata',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Введите текст:'),
        ),
    ]
