# Generated by Django 4.2.2 on 2023-06-24 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_line', '0003_textdata_duration_textdata_height_textdata_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdata',
            name='size_text',
            field=models.IntegerField(default=40, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Введите размер текста:'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='height',
            field=models.IntegerField(default=112, validators=[django.core.validators.MaxValueValidator(1980)], verbose_name='Введите ширину видео:'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='weight',
            field=models.IntegerField(default=112, validators=[django.core.validators.MaxValueValidator(1980)], verbose_name='Введите длину видео:'),
        ),
    ]
