# Generated by Django 4.2.2 on 2023-06-25 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_line', '0004_textdata_size_text_alter_textdata_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdata',
            name='duration',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Введите длительность видео (максимум 100 сек.):'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='height',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(1080)], verbose_name='Введите ширину видео (макисмум 1080 px):'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='size_text',
            field=models.IntegerField(default=40, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Введите размер текста, который будет представлен в видео (максимум 500):'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Введите текст, который будет представлен в видео:'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='weight',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(1920)], verbose_name='Введите длину видео (максимум 1920 px):'),
        ),
    ]
